[versions]
febit-devkit = '1.5.0'
febit-commons = '4.0.0'
febit-wit = '3.0.0-SNAPSHOT'

avro = '1.12.1'
calcite = '1.41.0'
flink = '1.20.3'
sqlline = '1.12.0'

assertj = '3.27.7'
junit = '6.0.2'
mockito = '5.21.0'

hierynomus-license = '0.16.1'

[libraries]
febit-commons-deps = { module = 'org.febit:febit-commons-dependencies', version.ref = 'febit-commons' }
assertj-bom = { module = 'org.assertj:assertj-bom', version.ref = 'assertj' }
junit-bom = { module = 'org.junit:junit-bom', version.ref = 'junit' }
mockito-bom = { module = 'org.mockito:mockito-bom', version.ref = 'mockito' }

avro = { module = 'org.apache.avro:avro', version.ref = 'avro' }
calcite-core = { module = 'org.apache.calcite:calcite-core', version.ref = 'calcite' }
flink = { module = 'org.apache.flink:flink-core', version.ref = 'flink' }
wit-core = { module = 'org.febit.wit:wit-core', version.ref = 'febit-wit' }
sqlline = { module = 'sqlline:sqlline', version.ref = 'sqlline' }


[plugins]
febit-bom = { id = 'org.febit.standard-bom', version.ref = 'febit-devkit' }
febit-codegen-module = { id = 'org.febit.codegen-module', version.ref = 'febit-devkit' }
febit-java = { id = 'org.febit.standard-java', version.ref = 'febit-devkit' }
febit-maven-publish = { id = 'org.febit.standard-maven-publish', version.ref = 'febit-devkit' }
license = { id = 'com.github.hierynomus.license', version.ref = 'hierynomus-license' }

